In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

data = np.array([[3,5],[7,4],[2,4]])
print(data)

#Way : 1
#mean = average
mean_val = data.mean(axis=0)
print(mean_val)

#Standard Deviation
std = data.std(axis=0)
print(std)

#Mean Removal : it means mean=0, std=1
final_val = data-mean_val
print(final_val)
# print(final_val.mean(axis = 0))
# print(final_val.std(axis = 0))

#Way:2
#scale()
final = preprocessing.scale(data)
print(final)
print(final.mean(axis = 0))
print(final.std(axis = 0))


[[3 5]
 [7 4]
 [2 4]]
[4.         4.33333333]
[2.1602469  0.47140452]
[[-1.          0.66666667]
 [ 3.         -0.33333333]
 [-2.         -0.33333333]]
[[-0.46291005  1.41421356]
 [ 1.38873015 -0.70710678]
 [-0.9258201  -0.70710678]]
[0.00000000e+00 5.92118946e-16]
[1. 1.]


In [ ]:
### df=pd.read_csv("csvdata.csv")
print(df)
data = df[['person','male','female']]
print("===========================")
print(data)

print(data.mean(axis=0))
print("===========================")
print(data.std(axis=0))

mean_removed_data = preprocessing.scale(data)
print(mean_removed_data.mean(axis=0))
print(mean_removed_data.std(axis=0))

# sacalling

In [3]:
import numpy as np
from sklearn import preprocessing

data = np.array([[3,5],[7,4],[2,4]])

#define A Scaller model Fro scalling The Data 
scaller_model= preprocessing.MinMaxScaler()

#Apply Data To The Model : Fit
op1=scaller_model.fit(data)

#Let The Model trasfer the data according to requirment : trasform
op2=op1.transform(data)

#print the result
print(op2)



[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


In [6]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = np.array([[3,5],[7,4],[2,4]])

#Define A Scaller Model For Scalling The Data\
scaller_model = preprocessing.MinMaxScaler()

#Apply The Data To Model And Let The Model trasfer The Data Accordingly
op = scaller_model.fit_transform(data)
print(op)

[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


# Normalization

In [11]:
data = np.array([[3,5],[7,4],[2,4]])
op = preprocessing.normalize(data,norm='l1')
print(op)

[[0.375      0.625     ]
 [0.63636364 0.36363636]
 [0.33333333 0.66666667]]
